program: train.py
method: bayes
metric:
  name: Ct_val_acc
  goal: maximize
parameters:
  cfg:
    values: ["./config/digit/config2.yaml"]
  lr_g:
    min: 0.0005
    max: 0.05
  lr_d:
    min: 0.0005
    max: 0.05